# ========================
# VALID CONFIG WAZUH 4.x
# ========================

analysisd.event_threads=4
analysisd.syscheck_threads=2
analysisd.rootcheck_threads=1
analysisd.winevt_threads=2

analysisd.decode_event_queue_size=32768
analysisd.decode_syscheck_queue_size=16384
analysisd.decode_rootcheck_queue_size=4096
analysisd.decode_winevt_queue_size=16384

analysisd.alerts_queue_size=16384
analysisd.archives_queue_size=16384

analysisd.fts_list_size=32
analysisd.fts_min_size_for_str=14

analysisd.log_fw=1

logcollector.vcheck_files=64
logcollector.max_lines=10000

remoted.recv_counter_flush=128

analysisd.debug=0
remoted.debug=0
authd.debug=0
execd.debug=0
monitord.debug=0
logcollector.debug=0
integrator.debug=0
wazuh_db.debug=0
wazuh_modules.debug=0
wazuh_clusterd.debug=0